version: '3'

services:
  libretv:
    image: bestzwei/libretv:latest
    container_name: libretv
    ports:
      - "8899:80"
    environment:
      - PASSWORD=111111          # 设置密码保护，留空则不启用
      - PROXY_URL=https://api.codetabs.com/v1/proxy?quest=  # CORS 代理，留空则内置 /proxy/
    restart: unless-stopped
    # 如需挂载数据目录可取消注释
    # volumes:
    #   - ./data:/usr/share/nginx/html/data