name: Auto Update from Upstream LibreTV

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨 2 点 UTC（北京时间上午 10 点）执行
  workflow_dispatch:      # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/LibreTV/libretv.git
          git fetch upstream

      - name: Merge upstream/main into your main
        run: |
          git checkout main
          git merge --ff-only upstream/main || echo "No changes to merge"

      - name: Push changes if any
        run: |
          git push origin main || echo "Nothing to push"
