name: Sync Upstream

on:
  schedule:
    - cron: "0 3 * * *"  # UTC时间每天凌晨3点运行
  workflow_dispatch:     # 支持手动触发

permissions:
  contents: write       # 授予推送权限

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        
        if ! git remote | grep -q upstream; then
          git remote add upstream https://github.com/LibreSpark/LibreTV.git
        fi

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout main
        git merge upstream/main --allow-unrelated-histories -m "🔄 Sync from upstream" -X theirs

    - name: Push changes
      run: git push origin main
      env:
        TOKEN: ${{ secrets.PAT || github.token }}
