name: 打包上传到dockerHub

on:
  push:
    branches:
      - main  # 当 master 分支有推送时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Docker Buildx（支持多平台构建，可选）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # 构建上下文（默认是当前目录）
          file: ./Dockerfile  # Dockerfile 的路径
          push: true  # 推送镜像到 Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/libretv:latest  # 镜像名称和标签
