name: Optimized Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/bestZwei/LibreTV.git  # 添加 upstream 远程仓库
          git fetch upstream main  # 拉取 upstream 的 main 分支

      - name: Check for upstream changes
        id: check_changes
        run: |
          if [ $(git rev-list --count HEAD..upstream/main) -eq 0 ]; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT

      - name: Sync upstream changes only if needed
        if: steps.check_changes.outputs.no_changes != 'true'
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: bestZwei/LibreTV
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: Log sync results
        if: always()
        run: |
          echo "Sync attempt completed. Changes detected: ${{ steps.check_changes.outputs.no_changes != 'true' }}"

      - name: Notify on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Upstream Sync Failed"
          body: |
            The upstream sync workflow has failed. Please review the logs.
          labels: "bug, sync-issue"
